package com.example.naturalopinion

fun botanicalData() : List<String> {
    val items_by_latin : ArrayList<String> = ArrayList()
    //latin list
    items_by_latin.add("Achillea millefolium (Yarrow)")
    items_by_latin.add("Aconitum napellus (Monkshood, Aconite)")
    items_by_latin.add("Acorus calamus (Sweetflag, Acorus)")
    items_by_latin.add("Aesculus hippocastanum (Horsechestnut)")
    items_by_latin.add("Agrimonia eupatorium (Agrimony)")
    items_by_latin.add("Alchemilla vulgaris (Lady's mantle)")
    items_by_latin.add("Aletris farinosa (True unicorn)")
    items_by_latin.add("Allium sativum (Garlic)")
    items_by_latin.add("Althea officinalis (Marshmallow)")
    items_by_latin.add("Ammi visnaga (Khella)")
    items_by_latin.add("Angelica sinensis (Dong quai)")
    items_by_latin.add("Arctium lappa (Burdock)")
    items_by_latin.add("Arctostaphylos uva ursi (Bearberry)")
    items_by_latin.add("Armoracia rusticana (Horseradish)")
    items_by_latin.add("Asclepias tuberosa (Pleurisy root)")
    items_by_latin.add("Astragalus membranaceus (Milk vetch)")
    items_by_latin.add("Atropa belladonna (Belladonna)")
    items_by_latin.add("Avena sativa (Oats)")

    items_by_latin.add("Baptisia tintoria (Wild indigo)")
    items_by_latin.add("Barosma betulina (Buchu)")
    items_by_latin.add("Berberis vulgaris (Barberry)")
    items_by_latin.add("Bryonia alba (Bryony)")
    items_by_latin.add("Bupleurum chinense (Thoroughwax)")

    items_by_latin.add("Calendula officinalis (Marigold)")
    items_by_latin.add("Camellia sinensis (Green tea)")
    items_by_latin.add("Capsicum frutescens (Cayenne, Red pepper)")
    items_by_latin.add("Caulophyllum thalictroides (Blue cohosh)")
    items_by_latin.add("Centella asiatica (Gota kola)")
    items_by_latin.add("Chamaelirium luteum (False unicorn)")
    items_by_latin.add("Chelidonium majus (Celandine)")
    items_by_latin.add("Chimaphilia umbellata (Pipsissewa)")
    items_by_latin.add("Chionanthus virginicus (Fringe tree)")
    items_by_latin.add("Cimicifuga racemosa (Black cohosh)")
    items_by_latin.add("Cinnamomum spp. (Cinnamon)")
    items_by_latin.add("Collinsonia canadensis (Stone root)")
    items_by_latin.add("Commiphora molmol (Myrrh)")
    items_by_latin.add("Commiphora mukul (Guggulu)")
    items_by_latin.add("Corydalis bulbosa (Corydalis)")
    items_by_latin.add("Crataegus oxycantha (Hawthorne)")
    items_by_latin.add("Curcuma longa (Tumeric)")
    items_by_latin.add("Cynara scolymus (Artichoke)")

    items_by_latin.add("Datura stramonium (Jimson weed, Thornapple)")
    items_by_latin.add("Dioscorea villosa (Wild yam)")

    items_by_latin.add("Echinacea angustifolia (Purple cone flower)")
    items_by_latin.add("Eleutherococcus senticosus (Siberian ginseng)")
    items_by_latin.add("Ephedra sinica (Ma huang)")
    items_by_latin.add("Equisetum arvense (Shave grass, Horsetail)")
    items_by_latin.add("Eriodictyon californicum (Yerba santa)")
    items_by_latin.add("Eschscholzia californica (California poppy)")
    items_by_latin.add("Euphrasia officinalis (Eyebright)")

    items_by_latin.add("Filipendula ulmaria (Meadowsweet)")
    items_by_latin.add("Foeniculum vulgare (Fennel)")
    items_by_latin.add("Fucus vesiculosus (Bladderwrack, Kelp)")

    items_by_latin.add("Galium aparine (Cleavers, Bed straw)")
    items_by_latin.add("Gelsemium sempervirens (Yellow jasmine, Gelsemium)")
    items_by_latin.add("Gentiana lutea (Gentian)")
    items_by_latin.add("Geranium maculatum (Wild geranium, Cranesbill)")
    items_by_latin.add("Ginkgo biloba (Ginkgo)")
    items_by_latin.add("Glycyrrhiza glabra (Licorice)")
    items_by_latin.add("Grindelia camporum (Gumweed)")
    items_by_latin.add("Gymnema sylvestre (Gymnema)")

    items_by_latin.add("Hamamelis virginiana (Witch hazel)")
    items_by_latin.add("Harpagophytum procumbens (Devil's claw, Grapple plant)")
    items_by_latin.add("Humulus lupulus (Hops)")
    items_by_latin.add("Hydrastis canadensis (Goldenseal)")
    items_by_latin.add("Hypericum perforatum (St. John's wort)")
    items_by_latin.add("Hyssopus officinalis (Hyssop)")

    items_by_latin.add("Inula helenium (Elecampane)")

    items_by_latin.add("Juniperis communis (Juniper)")

    items_by_latin.add("Larrea tridentata (Chapparrel, Creosote bush, Creosotum)")
    items_by_latin.add("Lavendula angustifolia (Lavender)")
    items_by_latin.add("Leonurus cardiaca (Motherwort)")
    items_by_latin.add("Ligusticum porteri (Osha)")
    items_by_latin.add("Linum usitatissimum (Flax, Linseed)")
    items_by_latin.add("Lobelia inflata (Indian tobacco, Puke weed)")
    items_by_latin.add("Lomatium disectum (Desert parsley)")

    items_by_latin.add("Marrubium vulgare (Horehound)")
    items_by_latin.add("Matricaria chamomilla (German chamomile)")
    items_by_latin.add("Medicago sativa (Alfalfa)")
    items_by_latin.add("Melaleuca alternifolia (Tea tree)")
    items_by_latin.add("Melissa officinalis (Lemon balm)")
    items_by_latin.add("Mentha piperita (Peppermint)")
    items_by_latin.add("Mitchella repens (Squawvine, Partridge berry)")
    items_by_latin.add("Momordica charantia (Bitter melon)")

    items_by_latin.add("Nepeta cataria (Catnip)")

    items_by_latin.add("Oplopanax horridum (Devil's club)")

    items_by_latin.add("Panax ginseng (Chinese ginseng, Korean ginseng)")
    items_by_latin.add("Passiflora incarnata (Passionflower)")
    items_by_latin.add("Pausinystalia yohimbe (Yohimbe)")
    items_by_latin.add("Petasites hybridus (Butterbur, Bladderdock, Bog Rhubarb)")
    items_by_latin.add("Petroselinum crispum (Parsley)")
    items_by_latin.add("Phytolacca decandra (Poke)")
    items_by_latin.add("Pimpinella anisum (Anise)")
    items_by_latin.add("Piper methysticum (Kava kava)")
    items_by_latin.add("Piscidia piscipula (Jamaican dogwood)")
    items_by_latin.add("Polygonum multiflorum (Fo-ti, He-shou-wu)")
    items_by_latin.add("Pygeum africanum (Pygeum)")

    items_by_latin.add("Rhamnus frangula (Buckthorn)")
    items_by_latin.add("Rhamnus purshiana (Cascara)")
    items_by_latin.add("Rheum officinalis (Rhubarb)")
    items_by_latin.add("Rosmarius officinalis (Rosemary)")
    items_by_latin.add("Rumex crispis (Yellow dock, Curly dock)")
    items_by_latin.add("Ruscus aculeatus (Butcher's broom)")

    items_by_latin.add("Salvia miltiorrhiza (Danshen)")
    items_by_latin.add("Salvia officinalis (Sage)")
    items_by_latin.add("Sambucus canadensis, nigra (Elder)")
    items_by_latin.add("Sanguinaria canadensia (Blood root)")
    items_by_latin.add("Schisandra chinensis (Wu wei zi)")
    items_by_latin.add("Scutellaria laterifolia (Skullcap)")
    items_by_latin.add("Serenoa repens (Saw palmetto)")
    items_by_latin.add("Silybum marianum (Milk thistle)")
    items_by_latin.add("Smilax sarsaparilla (Sarsaparilla)")
    items_by_latin.add("Spilanthes acmella (Paracress)")
    items_by_latin.add("Stellaria media (Chickweed)")
    items_by_latin.add("Sticta pulmonaria (Lungwort)")
    items_by_latin.add("Stillingia sylvatica (Queen's root)")
    items_by_latin.add("Symphytum officinale (Comfrey)")
    items_by_latin.add("Symplocarpus foetida (Skunk cabbage)")

    items_by_latin.add("Tabebuia impetiginosa (Pau d' arco)")
    items_by_latin.add("Tanacetum parthenium (Feverfew)")
    items_by_latin.add("Taraxacum officinale (Dandelion, Lion's tooth)")
    items_by_latin.add("Taxus brevifolia (Yew)")
    items_by_latin.add("Thuja plicata, occidentalis (Western cedar)")
    items_by_latin.add("Thymus vulgaris (Thyme)")
    items_by_latin.add("Tilia europaea (Linden flower, Lime blossom)")
    items_by_latin.add("Trifollium pratense (Red clover)")
    items_by_latin.add("Trigonella foenum-graecum (Fenugreek)")
    items_by_latin.add("Trillium erectum (Beth root)")
    items_by_latin.add("Tussilago farfara (Colt's foot)")

    items_by_latin.add("Ulmus fulva (Slippery elm, American elm)")
    items_by_latin.add("Urtica urens (Nettles)")
    items_by_latin.add("Usnea spp. (Old man's beard)")

    items_by_latin.add("Vaccinium myrtillus (Bilberry)")
    items_by_latin.add("Valeriana officinalis (Valerian)")
    items_by_latin.add("Verbascum thapsus (Mullein)")
    items_by_latin.add("Verbena officinalis (Vervain)")
    items_by_latin.add("Viburnum opulus (Cramp bark)")
    items_by_latin.add("Viscum alba (Mistletoe)")
    items_by_latin.add("Vitex agnus castus (Chaste tree, Monk's pepper)")
    items_by_latin.add("Withania somnifera (Ashwagandha)")

    items_by_latin.add("Yucca spp. (Yucca)")

    items_by_latin.add("Zanthoxylum clava-herculis (Southern prickly ash)")
    items_by_latin.add("Zea mays (Corn silk)")
    items_by_latin.add("Zingiber officinale (Ginger)")
    return items_by_latin
}